language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-23
    - extra-android-m2repository

before_install:
  - script/start_emulator.sh